### ISSUE TITLE
Stash indicator

### ISSUE THREAD

**Issue by sohlis** [CrisFeo/dotfiles#1]
It would be dope if you had an optional indicator `git stash` patches existing

**Comment by sohlis** [comment]
```
┌─┤(+) sjs-fix-broken-faq-and-redirect ├─┤() ~/Desktop/marketing-site
└─► 
```

maybe the plus is the indicator of Stashidness

**Comment by sohlis** [comment]
from @CrisFeo  IRL : `if [ "$(git stash list)" == '' ]; then echo yes; fi`

**Comment by CrisFeo** [comment]
I don't use stashes so I'm not gonna add that to this repo. However if you want them just replace the function of the same name with this bad boy:

``` bash
prompt-segment-git() {
  branch="$(git-current-branch)"
  hasStashes="$([ "$(git stash list)" != '' ] && echo '+')"
  if [ "$branch" != "" ]; then
    render-segment "prompt-color-git" "$hasStashes" "$branch"
  fi
}
```

**Comment by sohlis** [comment]
you rock @CrisFeo
